#!/bin/bash

[ "$(whoami)" != "root" ] && exec sudo -- "$0"

echo "#!/bin/bash

if [[ \$# -eq 1 ]]; then
	pkexec env DISPLAY=\$DISPLAY XAUTHORITY=\$XAUTHORITY \$1
else
	echo "gsudo: error: bad number of arguments."
fi" >> /usr/local/bin/gsudo

chmod +x /usr/local/bin/gsudo